export const ACTION_TYPES = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  ASYNC_LOAD: 'ASYNC_LOAD',
  FETCH_TEST_JSON: 'FETCH_TEST_JSON',
  FETCH_TEST_JSON_SUCCEEDED: 'FETCH_TEST_JSON_SUCCEEDED',
  FETCH_TEST_JSON_FAILED: 'FETCH_TEST_JSON_SUCCESS',
}
